### ISSUE TITLE
death event messages

### ISSUE THREAD

**Issue by madtomic** [Ratismal/MoneyThief#6]
![moneytheif](https://cloud.githubusercontent.com/assets/6004542/9318963/2db37df4-4517-11e5-9529-5c4ec30d81fc.png)

Is there a way to change the messages to match the ones from minecraft death messages?

Also, is there a way turn off the default death messages and replaced with the ones from MoneyThief?

**Comment by Ratismal** [comment]
You should be able to do both of these things in the config. You can customize both the message that is returned to the player, as well as the message broadcasted to the server. Check [this](https://i.gyazo.com/409ceb464f85d40d04a29065d006fd04.png) for reference. I haven't tested it yet, but pvemessage should work for deaths other than mob-kills-player. If not, get back to me and I'll fix it.

**Comment by madtomic** [comment]
I have another error while fighting Blaze.
http://pastebin.com/5XSj6hjq

**Comment by madtomic** [comment]
![mtmessages](https://cloud.githubusercontent.com/assets/6004542/9345648/1d6d4860-45e1-11e5-97ad-b2c0904bd890.png)

I just tried and no error this time. but messages are kinda funny. As you can see. =D
