### ISSUE TITLE
Errors from Miner's Insanity

### ISSUE THREAD

**Issue by madtomic** [Ratismal/MoneyThief#7]
Using this plugin with MoneyThief

http://dev.bukkit.org/bukkit-plugins/miners-insanity/

I get error when I died from insane.

http://pastebin.com/AArV64bg

Sometimes, it would said, You were killed by an arrow. Very weird.

**Comment by Ratismal** [comment]
Try using [this](http://dev.bukkit.org/bukkit-plugins/moneythief/files/23-money-thief-1-2-13/) version (version 1.2.13) to fix the error being generated. As for it saying you were killed by an arrow, I have no idea. This is most likely an issue with Miners Insanity not parsing their death events properly. Get back to me if version 1.2.13 doesn't work.

**Comment by madtomic** [comment]
Ok, I sent the same error to the author of miner's insanity. Maybe between this plugin and the other. We can get this all sorted.
